CRM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    )
from django.urls import path, include
from leads.views import landing_page, LandingPageView, SignupView, DashboardView, LeadsView, ContactListView, DealListView, ContactCreateView, ContactDetailView, ContactUpdateView, ContactDeleteView




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('deals/', DealListView.as_view(), name='deals'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace="agents")),
    path('contacts/', ContactListView.as_view(), name="contacts"),
    path('<int:pk>/contacts/', ContactDetailView.as_view(), name='contact-detail'),
    path('contacts/create/', ContactCreateView.as_view(), name='contact-create'),
    path('<int:pk>/contacts/update/', ContactUpdateView.as_view(), name='contact-update'),
    path('<int:pk>/contacts/delete/', ContactDeleteView.as_view(), name='contact-delete'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidp64>/<token>', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-ceomplete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import (
    LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView, AssignAgentView, CategoryListView, CategoryDetailView, LeadCategoryUpdateView, DealListView, DealDetailView, DealDeleteView,
    LeadsView, DealCreateView, DealUpdateView
)
app_name = "leads"

urlpatterns = [
    path('', LeadsView.as_view(), name='leads'),        
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('<int:pk>/category/', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>', CategoryDetailView.as_view(), name='category-detail'),
    path('deals/', DealListView.as_view(), name="lead-deal"),
    path('deals/create/', DealCreateView.as_view(), name="deal-create"),
    path('<int:pk>/deals/detail/', DealDetailView.as_view(), name="deal-detail"),
    path('<int:pk>/deals/update/', DealUpdateView.as_view(), name="deal-update"),
    path('<int:pk>/deals/delete/', DealDeleteView.as_view(), name="deal-delete"),
]

leads/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator
from django.utils.translation import gettext_lazy as _
from django.dispatch import receiver


class User(AbstractUser):
    is_organisor = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email

class Contact(models.Model):

    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    phone = models.CharField(max_length=20, null=True)
    email = models.EmailField(_("email"), max_length=254, blank=True, null=True)
    job_position = models.CharField(max_length=40, blank=True, null=True)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True, blank=True) 
    name = models.ForeignKey("Lead", on_delete=models.CASCADE, null=True, blank=True) 
    agent = models.ForeignKey("Agent", on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Lead(models.Model):
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey("Agent", on_delete=models.SET_NULL, null=True, blank=True)
    class Status(models.TextChoices):
        HIGH = 'New', 'New'
        REGULAR = 'Regular', 'Regular'
        LOW = 'Key', 'Key'
    status = models.CharField(
        max_length=10,
        choices=Status.choices,
        default=Status.REGULAR
    )

    name = models.CharField(max_length=40, default=None, blank=True, null=True)
    primary_contact = models.ForeignKey(
        Contact,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="primary_leads",
    )

    contacts = models.ManyToManyField(
        Contact,
        related_name="leads",
        blank=True,
    )

    def __str__(self):
        
        return self.name


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        # Znajdź profil admina (organizację, do której mają należeć wszyscy)
        try:
            admin_user = User.objects.filter(is_superuser=True).first()
            organisation_profile = admin_user.userprofile
        except Exception:
            organisation_profile = None

        # Tworzymy UserProfile nowego użytkownika i przypisujemy do tej samej organizacji
        UserProfile.objects.create(user=instance, organisation=organisation_profile)

class Deal(models.Model):
    name = models.CharField(max_length=40) #title for deal
    lead = models.ForeignKey("Lead", on_delete=models.SET_NULL, null=True, blank=True, related_name="deals") #name of company from Leads
    value = models.DecimalField(max_digits=10, decimal_places=2)
    close_date = models.DateField()
    agent = models.ForeignKey("Agent", on_delete=models.SET_NULL, null=True, blank=True)

    class Probability(models.TextChoices):
        LOW = '0-30', '0-30%'
        MEDIUM = '30-50', '30-50%'
        HIGH = '50-70', '50-70%'
        VERY_HIGH = '75-100', '75-100%'

    probability = models.CharField(
        max_length=10,
        choices=Probability.choices,
        default=Probability.LOW
        )
    class Status(models.TextChoices):
        CREATED = 'Created'
        IN_PROGRESS = 'In Progress'
        LOST = 'Lost'
        WON = 'Won'

    status = models.CharField(
        max_length=15,
        choices=Status.choices,
        default=Status.CREATED
    )
    contact = models.ForeignKey(
        "Contact",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="deals"
    )
    
    
    def __str__(self):
        return f"{self.name} ({self.get_probability_display()})"


class Category(models.Model):
    name = models.CharField(max_length=30)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


def post_user_create_signal(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)

post_save.connect(post_user_create_signal, sender=User)

leads/forms.py
from django import forms 
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import Lead, Agent, Deal, Contact

User = get_user_model()

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ('name', 'organisation', 'agent', 'status', 'primary_contact', 'contacts')
        exclude = ("organisation",)

class DealModelForm(forms.ModelForm):
    class Meta:
        model = Deal
        fields = ('name','lead', 'value', 'close_date','agent','probability', 'status','contact')
        widgets = {
            'close_date': forms.DateInput(attrs={
                'type': 'date',      
                'class': 'input',     
                'placeholder': 'Select a date',
            }),
        }

class ContactModelForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'phone','email','job_position', 'organisation','name', 'agent')
        exclude = ("organisation",)

class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    phone = forms.CharField()

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", )
        field_classes = {'username': UsernameField}

class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organisation=request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents

class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'status',
        )

leads/templates/leads/assign_agent.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'leads:lead-list' %}"> Back </a>
    <hr />
    <h1>Assign an agent to this lead</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> Submit </button>
    </form>
{% endblock content%}

leads/templates/leads/category_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
            These categories segment the leads
        </p>
    </div>
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Name</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Count</th>
          </tr>
        </thead>
        <tbody>
            <tr>
                <td class="px-4 py-3">Unassigned</td>
                <td class="px-4 py-3">{{ unassigned_lead_count }}</td>
            </tr>
         {% for category in category_list %}
            <tr>
                <td class="px-4 py-3">
                  <a href="{% url 'leads:category-detail' category.pk %}">{{ category.name }}</td></a>
                <td class="px-4 py-3">TODO count</td>
            </tr>
         {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>

{% endblock content %}

leads/templates/leads/contact_create.html
{% extends "base.html" %}

{% block content %}
    <div>
        <a class="content_button_back" href="{% url 'leads:lead-deal' %}">
            <span class="material-symbols-outlined">chevron_backward</span>
            Back
        </a>
    </div>
    <h1>Create a new deal</h1>
    <form method="post" class="create-form-container">
        {% csrf_token %}
        {{ form.as_p }}
   
        <button type="submit"> Submit </button>
    </form>
{% endblock content%}

leads/templates/leads/contact_delete.html
{% extends "base.html" %}

{% block content %}


        <form method="post" class="delete-form">
        <h3>Are you sure you want to delete deal: {{ contact.first_name }} {{ contact.last_name }}?</h3>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button-submit"> Submit </button>
        <p>
        <a href="{% url 'contact-detail' contact.pk %}" class="delete_button"> Back </a>
    </form>
{% endblock content%}

leads/templates/leads/contact_update.html
{% extends "base.html" %}

{% block content %}


<section>
    
  <div class="content">
    <div>
      <div class="detail_view">
      <div class="detail_view_header"> 
        <h1>{{ lead.name }}</h1>

</div>
          </div>
        <form class="update-form" method="post" action="{% url 'contact-update' contact.pk %}">
          {% csrf_token %}
          {{ form.as_p }}
                  <div></div>
                  <button class="content_button" type="submit">
                    <span class="material-symbols-outlined">save</span>
                    Save
                  </button>
            
        </form>

    
</section>

{% endblock content%}

leads/templates/leads/contacts.html
{% extends 'base.html' %}

{% block content %}



    <div class="dashboard">

    <div class="content">
        <div class="content_bar">
            <div class="content_text">
                <h1>Contacts</h1>
                <h2>Manage your customer contacts</h2>
            </div>
            <div>
                <a class="content_button" href="{% url 'contact-create' %}">
                <span class="material-symbols-outlined">add</span>
                Add Contact
                </a>
            </div>

        </div>
        {% include 'leads/contact_list.html' %}
    </div>
    </div>

{% endblock content %}

leads/templates/leads/deal_create.html
{% extends "base.html" %}

{% block content %}
    <div>
        <a class="content_button_back" href="{% url 'leads:lead-deal' %}">
            <span class="material-symbols-outlined">chevron_backward</span>
            Back
        </a>
    </div>
    <h1>Create a new deal</h1>
    <form method="post" class="create-form-container">
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <a class="button" href="{% url 'contact-create' %}">Add new contact</a>
        </div>
        
        <button type="submit"> Submit </button>
    </form>
{% endblock content%}

leads/templates/leads/deal_list.html
<section>

    <div class="search">
        <div class="search-input">
            <span class="material-symbols-outlined">search</span>
            <input type="search" name="search" class="input" placeholder="Search leads...">
        </div>
    </div>

    <div class="table">

        <div class="table_header">
            <div class="table_cell" data-type="text">
                <h2>Name</h2><span class="material-symbols-outlined">keyboard_arrow_down</span>
            </div>
            <div class="table_cell" data-type="text">
                <h2>Lead</h2><span class="material-symbols-outlined">keyboard_arrow_down</span>
            </div>
            <div class="table_cell" data-type="number">
                <h2>Value</h2><span class="material-symbols-outlined">keyboard_arrow_down</span>
            </div>
            <div class="table_cell" data-type="number">
                <h2>Probability</h2><span class="material-symbols-outlined">keyboard_arrow_down</span>
            </div>
            <div class="table_cell" data-type="date">
                <h2>Close date</h2><span class="material-symbols-outlined">keyboard_arrow_down</span>
            </div>
            <div class="table_cell" data-type="text">
                <h2>Owner</h2><span class="material-symbols-outlined">keyboard_arrow_down</span>
            </div>
            <div class="table_cell">
                <h2>Action</h2>
            </div>
        </div>

        {% if request.resolver_match.url_name == 'dashboard' %}

            {% for deal in top_deals %}
            <div class="table_row">
                <div class="table_cell" data-label="Name">{{ deal.name }}</div>
                <div class="table_cell" data-label="Lead">{{ deal.lead }}</div>
                <div class="table_cell" data-label="Value">${{ deal.value }}</div>
                <div class="table_cell" data-label="Probability">{{ deal.probability }}%</div>
                <div class="table_cell" data-label="Close date">{{ deal.close_date }}</div>
                <div class="table_cell" data-label="Owner">{{ deal.agent|default:"n/a" }}</div>
                <div class="table_cell" data-label="Action">
                    <a href="{% url 'leads:deal-detail' deal.pk %}">Details</a>
                </div>
            </div>
            {% endfor %}

        {% else %}

            {% for deal in deal_list %}
            <div class="table_row">
                <div class="table_cell" data-label="Name">{{ deal.name }}</div>
                <div class="table_cell" data-label="Lead">{{ deal.lead }}</div>
                <div class="table_cell" data-label="Value">${{ deal.value }}</div>
                <div class="table_cell" data-label="Probability">{{ deal.probability }}%</div>
                <div class="table_cell" data-label="Close date">{{ deal.close_date }}</div>
                <div class="table_cell" data-label="Owner">{{ deal.agent|default:"n/a" }}</div>
                <div class="table_cell" data-label="Action">
                    <a href="{% url 'leads:deal-detail' deal.pk %}">Details</a>
                </div>
            </div>

            {% empty %}
            <div class="table_row">
                <div class="table_cell">n/a</div>
                <div class="table_cell">n/a</div>
                <div class="table_cell">n/a</div>
                <div class="table_cell">n/a</div>
                <div class="table_cell">n/a</div>
                <div class="table_cell">n/a</div>
                <div class="table_cell">n/a</div>
            </div>
            {% endfor %}

        {% endif %}

    </div> 

</section>

leads/templates/leads/deal_update.html
{% extends "base.html" %}

{% block content %}


<section>
    
  <div class="content">
    <div>
      <div class="detail_view">
      <div class="detail_view_header"> 
        <h1>{{ deal.name }}</h1>

</div>
          </div>
        <form class="update-form" method="post" action="{% url 'leads:deal-update' deal.pk %}">
          {% csrf_token %}
          {{ form.as_p }}
                  <div></div>
                  <button class="content_button" type="submit">
                    <span class="material-symbols-outlined">save</span>
                    Save
                  </button>
            
        </form>

    
</section>

{% endblock content%}

leads/templates/leads/deals.html
{% extends 'base.html' %}

{% block content %}

{% load number_format %}
    <div class="content">
        <div class="content_bar">
            <div class="content_text">
                <h1>Deals</h1>
                <h2>Track your sales pipeline and opportunities</h2>
            </div>
            <div>
                <a class="content_button" href="{% url 'leads:deal-create' %}">
                <span class="material-symbols-outlined">add</span>
                Add Deal
                </a>
            </div>
        </div>
        <div>
            <div class="content_stats">
                <div class="box">
                    <div class="box_text">
                        <h2>Created</h2>
                        <h1>${{ total_created|readable_number }}</h1>
                        <h2>{{ total_created_count }} deal(s)</h2>
                    </div>
                    <span class="material-symbols-outlined">add</span>
                </div>
                <div class="box">
                    <div class="box_text">
                        <h2>In Progress</h2>
                        <h1>${{ total_in_progress|readable_number }}</h1>
                        <h2>{{ total_in_progress_count }} deal(s)</h2>
                    </div>
                    <span class="material-symbols-outlined">trending_flat</span>
                </div>
                <div class="box">
                    <div class="box_text">
                        <h2>Lost</h2>
                        <h1>${{ total_lost|readable_number }}</h1>
                        <h2>{{ total_lost_count }} deal(s)</h2>
                    </div>
                    <span class="material-symbols-outlined">trending_down</span>
                </div>
                <div class="box">
                    <div class="box_text">
                        <h2>Won</h2>
                        <h1>${{ total_won|readable_number }}</h1>
                        <h2>{{ total_won_count }} deal(s)</h2>
                    </div>
                    <span class="material-symbols-outlined">trending_up</span>
                </div>
            </div>
            <div>
                {% include 'leads/deal_list.html' %}
            </div>
        </div>
    </div>
{% endblock content %}

leads/templates/leads/lead_category_update.html
{% extends "base.html" %}

{% block content %}

  <section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
        <div class="flex mb-4">
            <a href="{% url 'leads:lead-detail' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                Overview
            </a>
            <a href="{% url 'leads:lead-category-update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                Category
            </a>
            <a href="{% url 'leads:lead-update' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                Update Details
            </a>
        </div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit"> Submit </button>
            </form>
            <a href="{% url 'leads:lead-delete' lead.pk %}" class="w-1/2 mt-3 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                Delete
            </a>
        </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>

{% endblock content%}

leads/templates/leads/lead_create.html
{% extends "base.html" %}

{% block content %}
    <div>
        <a class="content_button_back" href="{% url 'leads:leads' %}">
            <span class="material-symbols-outlined">chevron_backward</span>
            Back
        </a>
    </div>
    <h1>Create a new lead</h1>
    <form method="post" class="create-form-container">
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <a class="button" href="{% url 'contact-create'%}">Add new contact</a>
        </div>
        
        <button type="submit"> Submit </button>
    </form>
{% endblock content%}

leads/templates/leads/lead_detail.html
{% extends "base.html" %}

{% block content %}
<section>
  <div class="content">
    <div>
      <div class="detail_view">
      <div class="detail_view_header"> 
        <h1>{{ lead.name }}</h1>
            <div>
               <a class="content_button" href="{% url 'leads:lead-update' lead.pk %}">
                  <span class="material-symbols-outlined">edit</span>
                  Edit
               </a>
               
      
            </div>
          </div>
        <div class="table">
          <div class="table_row">
            <div class="table_cell">Name</div>
            <div class="table_cell">{{ lead.name }}</div>
          </div>
          <div class="table_row">
            <div class="table_cell">Agent</div>
            <div class="table_cell">{{ lead.agent }}</div>
          </div>
            <div class="table_row">
            <div class="table_cell">Status</div>
            <div class="table_cell">{{ lead.status }}</div>
          </div>
           <div class="table_row">
            <div class="table_cell">Primary Contact</div>
            <div class="table_cell">{{ lead.primary_contact }}</div>
          </div>
          <div class="table_row">
            <div class="table_cell">Agent</div>
            <div class="table_cell">{{ lead.agent }}</div>
          </div>
           <div class="table_row">
            <div class="table_cell">Contacts</div>
            <div class="table_cell">
              {% for contact in lead.contacts.all %}
              {{ contact.first_name }} {{ contact.last_name }}{% if not forloop.last %}, {% endif %}
              {% empty %}
              No contacts
              {% endfor %}
            </div>
          </div>
    </div>
     <p>
      
     <a class="delete_button" href="{% url 'leads:lead-delete' lead.pk %}">Delete
        <span class="material-symbols-outlined">delete</span>
     </a>
</div>
    <p></p>
    <div class="detail_view">
      <div class="detail_view_header"> 
  
        <h3>Deals assigned to: {{ lead.name }}</h3>
            
      </div>


  <div class="table">
    {% for deal in deals %}
      <div class="table_row">
        <div class="table_cell">{{ deal.name }}</div>
        <div class="table_cell">{{ deal.value }}</div>
      </div>
    {% endfor %}
  </div>
</div>

</section>
{% endblock content%}

leads/templates/leads/lead_update.html
{% extends "base.html" %}

{% block content %}

<!--           <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit"> Submit </button>
            </form>
            <a href="{% url 'leads:lead-delete' lead.pk %}" class="w-1/2 mt-3 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                Delete
            </a>
        </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>
--> 



<section>
    
  <div class="content">
    <div>
      <div class="detail_view">
      <div class="detail_view_header"> 
        <h1>{{ lead.name }}</h1>

</div>
          </div>
        <form class="update-form" method="post" action="{% url 'leads:lead-update' lead.pk %}">
          {% csrf_token %}
          {{ form.as_p }}
                  <div></div>
                  <button class="content_button" type="submit">
                    <span class="material-symbols-outlined">save</span>
                    Save
                  </button>
            
        </form>

    
</section>

{% endblock content%}