CRM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    )
from django.urls import path, include
from leads.views import landing_page, LandingPageView, SignupView, DashboardView, LeadsView, ContactListView, DealListView, ContactCreateView, ContactDetailView, ContactUpdateView, ContactDeleteView




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('deals/', DealListView.as_view(), name='deals'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace="agents")),
    path('contacts/', ContactListView.as_view(), name="contacts"),
    path('<int:pk>/contacts/', ContactDetailView.as_view(), name='contact-detail'),
    path('contacts/create/', ContactCreateView.as_view(), name='contact-create'),
    path('<int:pk>/contacts/update/', ContactUpdateView.as_view(), name='contact-update'),
    path('<int:pk>/contacts/delete/', ContactDeleteView.as_view(), name='contact-delete'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidp64>/<token>', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-ceomplete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import (
    LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView, AssignAgentView, CategoryListView, CategoryDetailView, LeadCategoryUpdateView, DealListView, DealDetailView, DealDeleteView,
    LeadsView, DealCreateView, DealUpdateView
)
app_name = "leads"

urlpatterns = [
    path('', LeadsView.as_view(), name='leads'),        
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('<int:pk>/category/', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>', CategoryDetailView.as_view(), name='category-detail'),
    path('deals/', DealListView.as_view(), name="lead-deal"),
    path('deals/create/', DealCreateView.as_view(), name="deal-create"),
    path('<int:pk>/deals/detail/', DealDetailView.as_view(), name="deal-detail"),
    path('<int:pk>/deals/update/', DealUpdateView.as_view(), name="deal-update"),
    path('<int:pk>/deals/delete/', DealDeleteView.as_view(), name="deal-delete"),
]

leads/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator
from django.utils.translation import gettext_lazy as _
from django.dispatch import receiver


class User(AbstractUser):
    is_organisor = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email

class Contact(models.Model):

    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    phone = models.CharField(max_length=20, null=True)
    email = models.EmailField(_("email"), max_length=254, blank=True, null=True)
    job_position = models.CharField(max_length=40, blank=True, null=True)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True, blank=True) 
    name = models.ForeignKey("Lead", on_delete=models.CASCADE, null=True, blank=True) 
    agent = models.ForeignKey("Agent", on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Lead(models.Model):
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey("Agent", on_delete=models.SET_NULL, null=True, blank=True)
    class Status(models.TextChoices):
        HIGH = 'New', 'New'
        REGULAR = 'Regular', 'Regular'
        LOW = 'Key', 'Key'
    status = models.CharField(
        max_length=10,
        choices=Status.choices,
        default=Status.REGULAR
    )

    name = models.CharField(max_length=40, default=None, blank=True, null=True)
    primary_contact = models.ForeignKey(
        Contact,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="primary_leads",
    )

    contacts = models.ManyToManyField(
        Contact,
        related_name="leads",
        blank=True,
    )

    def __str__(self):
        
        return self.name


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        # Znajdź profil admina (organizację, do której mają należeć wszyscy)
        try:
            admin_user = User.objects.filter(is_superuser=True).first()
            organisation_profile = admin_user.userprofile
        except Exception:
            organisation_profile = None

        # Tworzymy UserProfile nowego użytkownika i przypisujemy do tej samej organizacji
        UserProfile.objects.create(user=instance, organisation=organisation_profile)

class Deal(models.Model):
    name = models.CharField(max_length=40) #title for deal
    lead = models.ForeignKey("Lead", on_delete=models.SET_NULL, null=True, blank=True, related_name="deals") #name of company from Leads
    value = models.DecimalField(max_digits=10, decimal_places=2)
    close_date = models.DateField()
    agent = models.ForeignKey("Agent", on_delete=models.SET_NULL, null=True, blank=True)

    class Probability(models.TextChoices):
        LOW = '0-30', '0-30%'
        MEDIUM = '30-50', '30-50%'
        HIGH = '50-70', '50-70%'
        VERY_HIGH = '75-100', '75-100%'

    probability = models.CharField(
        max_length=10,
        choices=Probability.choices,
        default=Probability.LOW
        )
    class Status(models.TextChoices):
        CREATED = 'Created'
        IN_PROGRESS = 'In Progress'
        LOST = 'Lost'
        WON = 'Won'

    status = models.CharField(
        max_length=15,
        choices=Status.choices,
        default=Status.CREATED
    )
    contact = models.ForeignKey(
        "Contact",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="deals"
    )
    
    
    def __str__(self):
        return f"{self.name} ({self.get_probability_display()})"


class Category(models.Model):
    name = models.CharField(max_length=30)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


def post_user_create_signal(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)

post_save.connect(post_user_create_signal, sender=User)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght@300;700&family=Material+Symbols+Rounded:wght@400;700&display=swap" />
    
</head>
<body>
    <div class="main">
        {% include 'navbar.html' %}
        <div class="content-wrapper">
            {% include 'sidebar.html'%}
            <div class="content">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>
    {% include "scripts.html" %}
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}

{% block content %}

{% load number_format %}

<div class="dashboard">


    <div class="content">
        <div class="content_bar">
            <div class="content_text">
                <h1>Dashboard</h1>
                <h2>Welcome back! Here's your sales overview</h2>
            </div>
            <div>
              <a class="content_button" href="{% url 'leads:deal-create' %}">
                <span class="material-symbols-outlined">add</span>
               Add Deal 
            </a>
            </div>
        </div>
        <div class="content_stats">
            <div class="box">
                <div class="box_text">
                    <h2>Total Leads</h2>
                    <h1>{{ leads_count }}</h1>
                </div>
                <span class="material-symbols-outlined">target</span>
            </div>
            <div class="box">
                <div class="box_text">
                    <h2>Active Deals</h2>
                    <h1>{{ deals_count }}</h1>
                </div>
                <span class="material-symbols-outlined">account_circle</span>
            </div>
            <div class="box">
                <div class="box_text">
                    <h2>Revenue</h2>
                    <h1>${{ deals_total_value|readable_number }}</h1>
                </div>
                <span class="material-symbols-outlined">payments</span>
            </div>
             <div class="box">
                <div class="box_text">
                    <h2>Conversion Rate</h2>
                    <h1>{{ conversion_rate }}%</h1>
                </div>
                <span class="material-symbols-outlined">finance_mode</span>
            </div>
        </div>
        <div>
            <h1>Top Deals</h1>
            {% include 'leads/deal_list.html' %}
        </div>
    </div>
</div>
{% endblock content %}

templates/landing.html
{% load static %}

<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght@800&family=Material+Symbols+Rounded:wght@800&display=swap" />
    
</head>
<body>
  <section class="welcome">
        {% include "registration/login.html" %}
  </section>
    {% include "scripts.html" %}
</body>
</html>

templates/navbar.html
<div class="navbar-mobile">
  <header class="navbar">
      <div class="menu" id="menuToggle" aria-label="open-menu">
            <span class="line"></span>
            <span class="line"></span>
      </div>
      <div class="brand">
        <span class="title">SalesPro</span>
      </div>
      <div class="account">
        <span class="material-symbols-outlined" id="accountToggle">account_circle</span>
      </div>
  </header>
  
  <div class="account-details" id="mobileAccount">
      {% if request.user.is_authenticated %}
        <div>Logged in as: {{ request.user.username }}</div>
        <a href="{% url 'landing-page' %}">
          Logout
        </a> 
      {% else %}
        <a href="{% url 'login' %}">
          Login
        </a> 
      {% endif %}
  </div>

</div>


<div class="navbar-desktop">
  <header class="navbar">
    <div class="sub-navbar">
      <div class="brand">
        <span class="material-symbols-outlined">target</span>
        <span class="title">SalesPro</span>
      </div>
      <nav class="nav-links">
    
      
      {% if request.user.is_authenticated %}
        Logged in as: {{ request.user.username }}
        <a href="{% url 'landing-page' %}">
          Logout
        </a> 
      {% else %}
        <a href="{% url 'login' %}">
          Login
        </a> 
      {% endif %}
      </nav>
    </div>
  </header>
</div>

templates/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}"></script>

templates/second_page.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Moja strona</title>
</head>
<body>
    <h1>Hello world</h1>
    <p1>second page</p1>
    <ul>
        {% for lead in leads%}
        <li>{{ lead}}</li>
        {% endfor %}
    </ul>
    
   
</body>
</html>

templates/sidebar.html
   
<div class="sidebar-mobile">
    <div class="sidebar" id="mobileMenu">
        {% if request.user.is_authenticated %}
        <a class="{% if request.resolver_match.url_name == 'dashboard' %}active{% endif %}" href="{% url 'dashboard' %}">
            Dashboard
        </a>
        <a href="{% url 'leads:leads' %}" class="{% if request.resolver_match.url_name == 'leads' %}active{% endif %}">
            Leads
        </a>
        <a href="{% url 'contacts'%}" class="{% if request.resolver_match.url_name == 'contacts' %}active{% endif %}">
            Contacts
        </a>
        <a href="{% url 'deals' %}" class="{% if request.resolver_match.url_name == 'deals' %}active{% endif %}">
        Deals
        </a>

        {% endif %}
    </div>
</div>

<div class="sidebar-desktop">    
    <div class="sidebar">
        {% if request.user.is_authenticated %}
        <a class="{% if request.resolver_match.url_name == 'dashboard' %}active{% endif %}" href="{% url 'dashboard' %}">
            <span class="material-symbols-outlined">dashboard</span>
            Dashboard
        </a>
        <a href="{% url 'leads:leads' %}" class="{% if request.resolver_match.url_name == 'leads' %}active{% endif %}">
            <span class="material-symbols-outlined">target</span>
            Leads
        </a>
        <a href="{% url 'contacts'%}" class="{% if request.resolver_match.url_name == 'contacts' %}active{% endif %}">
            <span class="material-symbols-outlined">account_circle</span>
            Contacts
        </a>
        <a href="{% url 'deals' %}" class="{% if request.resolver_match.url_name == 'deals' %}active{% endif %}">
        <span class="material-symbols-outlined">payments</span>
        Deals
        </a>

        {% endif %}
    </div>
</div>